### ISSUE TITLE
Application is not waiting for bootstrap

### ISSUE THREAD

**Issue by stsje** [peppertech/vdomtraining#1]
### Issue
The app is not waiting for the application to finish bootstrapping before mounting the preact app.
To reproduce: Simply add an `<oj-list-view data={dataProvider}>` to the app component (first rendered component), and it will occasionally fail with the error:
```
Uncaught JetElementError: oj-list-view with id '': Error while parsing parsing attribute data. Error: Unable to parse data='[object Object]' for oj-list-view with id ''       to a object.
```

### The fix
Bootstrap the application the same way as Knockout apps
```
// import './components/app';

import * as Bootstrap from 'ojs/ojbootstrap';

Bootstrap.whenDocumentReady().then(async () => {
  import('./components/app');
});
```

**Comment by peppertech** [comment]
This shouldn't be needed in the later versions as there is this at the bottom of the app.tsx file now.

```
import Context = require("ojs/ojcontext");

...

  componentDidMount() {
    Context.getPageContext().getBusyContext().applicationBootstrapComplete();
  }
```

**Comment by peppertech** [comment]
Latest version of the app should not have this problem now.
